export const translations = {
    en: {
        header: {
            welcome: "WELCOME,",
            name: "YJ!",
            subtitle: "How are you sleeping these days?",
            description1: "Welcome to your personal sleep world — powered by your Galaxy Watch sleep data, where every night becomes a tiny piece of your story.",
            description2: "This is Your Personalized Sleep Intelligence Dashboard.",
            description3: "Let's dive into your sleep journey!",
            navTitle: "How to Use Your Dashboard",
            calendar: {
                title: "Sleep Calendar",
                desc: "Get an instant overview of your daily sleep quality through intuitive color-coded visuals. Click any date to dive into detailed information."
            },
            analysis: {
                title: "Sleep Analysis",
                desc: "Uncover trends and patterns in your sleep data. View your stats overall or monthly to understand how your sleep evolves over time."
            },
            insights: {
                title: "AI Insights",
                desc: "Receive personalized recommendations generated by AI. Identify habits, patterns, and actions that can help you sleep better."
            }
        },
        calendar: {
            title: "Sleep Calendar",
            description: "Check your daily sleep quality at a glance. Click on any date to explore detailed metrics and trends.",
            month: "Month",
            year: "Year",
            goalSleepTime: "Goal Sleep Time",
            weekdays: "Weekdays",
            weekend: "Weekend",
            free: "Free",
            selectDate: "Select a date to see details!",
            colorGuide: "Each calendar day is colored based on your sleep score!",
            scoreRanges: {
                veryLow: "0–25: A very poor sleep day",
                low: "26–50: Not a great night, but it's fine!",
                medium: "51–75: A fairly good night's rest!",
                high: "76–100: Slept great! Fully recharged!"
            },
            guideNote: "The sleep score is automatically calculated by your Galaxy Watch based on your daily sleep data.",
            sleepDetails: "Sleep Details",
            bedTime: "BED TIME",
            wakeTime: "WAKE TIME",
            remSleep: "REM Sleep",
            lightSleep: "Light Sleep",
            timeToFallAsleep: "Time to Fall Asleep",
            weekendFree: "Weekend - Free schedule!",
            sleptLater: "later",
            sleptEarlier: "earlier!",
            wokeLater: "later",
            wokeEarlier: "earlier!",
            comments: {
                veryLow: "Rough night, huh? Your body didn't get enough quality rest. Take it slow today and recharge",
                low: "Not your best sleep, but that's okay. Maybe stress or timing threw things off a bit. Try winding down earlier tonight",
                medium: "Decent rest! You slept fine, but there's still room to feel more refreshed. Keep up your rhythm",
                high: "Your sleep was balanced and restorative. Let's keep this healthy rhythm going"
            }
        },
        analysis: {
            title: "Sleep Analysis",
            description: "View your stats overall or monthly to understand how your sleep evolves over time.",
            overall: "Overall",
            monthly: "Monthly",
            weekday: "Weekday",
            weekend: "Weekend",
            correlationTitle: "What Affects Your Sleep the Most?",
            correlationDesc: "Larger absolute values indicate stronger influence: positive correlations improve sleep quality, while negative ones reduce it.",
            correlationMatrix: "Correlation Matrix",
            topCorrelatedSleepScore: "Top Correlated with Sleep Score",
            topCorrelatedEfficiency: "Top Correlated with Efficiency",
            features: {
                duration: "Duration",
                deepSleep: "Deep Sleep",
                lightSleep: "Light Sleep",
                latency: "Latency",
                score: "Score",
                physicalRecovery: "Physical Recovery",
                awakening: "Awakening",
                efficiency: "Efficiency",
                mentalRecovery: "Mental Recovery"
            },
            featureDescriptions: {
                latency: "Latency: Time it takes to fall asleep from when you lie down",
                physicalRecovery: "Physical Recovery: Deep sleep rate (%) in sleep duration",
                awakening: "Awakening: Awake rate (%) in sleep duration",
                mentalRecovery: "Mental Recovery: Rate (%) of REM sleep consistency"
            },
            sleepTimingTitle: "Sleep Timing Regularity",
            sleepTimingDesc: "The closer the data points cluster around the average line, the higher the regularity/ consistency of your bed and wake times throughout the month."
        },
        insights: {
            title: "AI Insights",
            description: "Receive personalized, AI-generated recommendations to identify patterns and actions for optimal sleep.",
            keyInsightsTitle: "Key Insights of your Sleep Quality",
            recommendationsTitle: "Recommendations for Optimal Sleep",
            insight1: {
                title: "Strongest Sleep Score Drivers : ",
                deepSleepRate: "Deep Sleep Rate",
                remConsistency: "REM Consistency Rate",
                point1: {
                    part1: "Deep Sleep Rate (physical_recovery)",
                    part2: ": Shows the highest positive correlation",
                    part3: "(0.84)",
                    part4: "with your Sleep Score."
                },
                point2: {
                    part1: "REM Consistency Rate (mental_recovery)",
                    part2: ": This is the second factor that positively affects",
                    part3: "(0.76)",
                    part4: "your Sleep Score."
                },
                point3: "To achieve a high sleep score, maximizing the Deep Sleep Rate and ensuring high consistency (particularly in the REM stage) are crucial for optimal sleep quality."
            },
            insight2: {
                title: "Impact of Fragmentation : ",
                awakeRate: "Awake Rate",
                point1: {
                    part1: "Awake Rate",
                    part2: ": The high Awake Rate (movement_awakening) is the primary cause",
                    part3: "(-0.96)",
                    part4: "of any loss in your sleep efficiency."
                },
                point2: "Reducing the amount of time you spend awake or lightly stirring is crucial for maximizing your efficiency."
            },
            insight3: {
                titleNumber: "3.",
                titlePart1: "Deep Sleep",
                titlePart2: "is the Foundation for",
                titlePart3: "Mental Recovery",
                point1: {
                    part1: "There is strong positive correlation (0.86) between",
                    part2: "Deep Sleep Duration(total_rem_duration)",
                    part3: "and",
                    part4: "REM Consistency Rate (Mental Recovery)",
                    part5: "."
                },
                point2: "Securing sufficient Deep Sleep is essential for boosting the consistency of your REM sleep and promoting mental recovery."
            },
            rec1: {
                title: "Prioritize Total Sleep Time",
                point1: "Your current 6 hours and 39 minutes is too short.",
                point2: "Sleep Score has a moderate correlation with duration (0.49).",
                point3: "Aim to consistently increase your time in bed by 15–30 minutes to achieve 7 hours or more of total sleep."
            },
            rec2: {
                title: "Minimize Sleep Disruption",
                point1: {
                    part1: "The high",
                    part2: "Awake Rate (17.0%)",
                    part3: "indicates an issue with continuous sleep."
                },
                point2: "Improve your sleep hygiene by avoiding caffeine and alcohol 2–3 hours before bedtime.",
                point3: "Ensure your bedroom temperature is slightly cool to prevent restlessness and reduce the Awake Rate."
            },
            rec3: {
                title: "Optimize REM Quality",
                deepSleepLabel: "For Deep Sleep Rate:",
                remLabel: "For REM Consistency Rate:",
                point1: "Practice light relaxation before sleep to lower your heart rate and accelerate entry into deep rest.",
                point2: "Ensure your sleeping environment is completely dark and quiet to prevent disturbances durning sleep stages."
            }
        },
        footer: {
            copyright: "© 2025 Yoonjae Oh. All rights reserved."
        }
    },
    ko: {
        header: {
            welcome: "환영합니다,",
            name: "YJ!",
            subtitle: "요즘 잠은 잘 주무시나요?",
            description1: "갤럭시 워치 수면 데이터로 구동되는 나만의 수면 세계에 오신 것을 환영합니다. 매일 밤이 당신의 이야기의 작은 조각이 됩니다.",
            description2: "이것은 당신만을 위한 개인화된 수면 인텔리전스 대시보드입니다.",
            description3: "당신의 수면 여정을 함께 탐험해봅시다!",
            navTitle: "대시보드 사용 방법",
            calendar: {
                title: "수면 캘린더",
                desc: "직관적인 색상 코드로 일일 수면 품질을 한눈에 파악하세요. 날짜를 클릭하면 상세 정보를 확인할 수 있습니다."
            },
            analysis: {
                title: "수면 분석",
                desc: "수면 데이터의 트렌드와 패턴을 발견하세요. 전체 또는 월별 통계를 보면서 시간에 따른 수면 변화를 이해할 수 있습니다."
            },
            insights: {
                title: "AI 인사이트",
                desc: "AI가 생성한 맞춤형 권장사항을 받아보세요. 더 나은 수면을 위한 습관, 패턴, 그리고 행동을 식별할 수 있습니다."
            }
        },
        calendar: {
            title: "수면 캘린더",
            description: "일일 수면 품질을 한눈에 시각화합니다. 날짜를 클릭하여 상세한 지표와 트렌드를 확인하세요.",
            month: "월별",
            year: "연도별",
            goalSleepTime: "목표 수면 시간",
            weekdays: "평일",
            weekend: "주말",
            free: "자유",
            selectDate: "날짜를 선택하여 세부 정보를 확인하세요!",
            colorGuide: "각 날짜는 수면 점수에 따라 색상으로 표시됩니다!",
            scoreRanges: {
                veryLow: "0–25: 매우 좋지 않은 수면",
                low: "26–50: 그다지 좋지 않지만 괜찮습니다!",
                medium: "51–75: 꽤 좋은 수면!",
                high: "76–100: 완벽한 수면! 충분히 회복되었습니다!"
            },
            guideNote: "수면 점수는 갤럭시 워치가 일일 수면 데이터를 기반으로 자동 계산합니다.",
            sleepDetails: "수면 상세 정보",
            bedTime: "취침 시각",
            wakeTime: "기상 시각",
            remSleep: "REM 수면",
            lightSleep: "얕은 수면",
            timeToFallAsleep: "입면 시간",
            weekendFree: "주말 - 자유 일정!",
            sleptLater: "늦게 잠",
            sleptEarlier: "일찍 잠!",
            wokeLater: "늦게 기상",
            wokeEarlier: "일찍 기상!",
            comments: {
                veryLow: "힘든 밤이었네요. 몸이 충분한 양질의 휴식을 취하지 못했습니다. 오늘은 천천히 보내며 재충전하세요",
                low: "최고의 수면은 아니었지만 괜찮습니다. 스트레스나 타이밍이 조금 영향을 준 것 같아요. 오늘 밤은 일찍 마무리해보세요",
                medium: "괜찮은 휴식이었어요! 잘 잤지만 더 상쾌하게 느낄 여지는 있습니다. 이 리듬을 유지하세요",
                high: "균형 잡히고 회복적인 수면이었습니다. 이 건강한 리듬을 계속 유지해봅시다"
            }
        },
        analysis: {
            title: "수면 분석",
            description: "포괄적인 지표와 시각화를 통해 수면 패턴을 깊이 있게 분석합니다.",
            overall: "전체",
            monthly: "월별",
            weekday: "평일",
            weekend: "주말",
            correlationTitle: "수면에 가장 큰 영향을 미치는 요소는?",
            correlationDesc: "절대값이 클수록 영향력이 강함을 나타냅니다: 양의 상관관계는 수면 품질을 향상시키고, 음의 상관관계는 감소시킵니다.",
            correlationMatrix: "상관관계 매트릭스",
            topCorrelatedSleepScore: "수면 점수와 가장 상관성 높은 요인",
            topCorrelatedEfficiency: "수면 효율성과 가장 상관성 높은 요인",
            features: {
                duration: "수면 시간",
                deepSleep: "깊은 수면",
                lightSleep: "얕은 수면",
                latency: "입면 시간",
                score: "점수",
                physicalRecovery: "신체 회복",
                awakening: "각성",
                efficiency: "효율성",
                mentalRecovery: "정신 회복"
            },
            featureDescriptions: {
                latency: "입면 시간: 누운 후 잠들기까지 걸리는 시간",
                physicalRecovery: "신체 회복: 전체 수면 시간 중 깊은 수면 비율 (%)",
                awakening: "각성: 전체 수면 시간 중 깨어있는 비율 (%)",
                mentalRecovery: "정신 회복: REM 수면 일관성 비율 (%)"
            },
            sleepTimingTitle: "수면 타이밍 규칙성",
            sleepTimingDesc: "데이터 포인트가 평균선 주위에 가까이 모일수록 한 달 동안 취침 및 기상 시간의 규칙성/일관성이 높습니다."
        },
        insights: {
            title: "AI 인사이트",
            description: "AI가 생성한 맞춤형 권장사항을 통해 수면 개선을 위한 패턴과 행동을 파악하세요.",
            keyInsightsTitle: "수면 품질에 대한 주요 인사이트",
            recommendationsTitle: "최적의 수면을 위한 권장사항",
            insight1: {
                title: "가장 강력한 수면 점수 요인 : ",
                deepSleepRate: "깊은 수면 비율",
                remConsistency: "REM 일관성 비율",
                point1: {
                    part1: "깊은 수면 비율 (신체 회복)",
                    part2: ": 수면 점수와 가장 높은 양의 상관관계",
                    part3: "(0.84)",
                    part4: "를 보입니다."
                },
                point2: {
                    part1: "REM 일관성 비율 (정신 회복)",
                    part2: ": 수면 점수에 두 번째로 긍정적인 영향",
                    part3: "(0.76)",
                    part4: "을 미치는 요소입니다."
                },
                point3: "높은 수면 점수를 달성하려면 깊은 수면 비율을 최대화하고 (특히 REM 단계에서) 높은 일관성을 유지하는 것이 중요합니다."
            },
            insight2: {
                title: "수면 분절의 영향 : ",
                awakeRate: "각성 비율",
                point1: {
                    part1: "각성 비율",
                    part2: ": 높은 각성 비율(움직임_각성)은 수면 효율성 손실의 주요 원인",
                    part3: "(-0.96)",
                    part4: "입니다."
                },
                point2: "깨어있거나 가볍게 뒤척이는 시간을 줄이는 것이 효율성을 극대화하는 데 중요합니다."
            },
            insight3: {
                titleNumber: "3.",
                titlePart1: "깊은 수면",
                titlePart2: "은",
                titlePart3: "정신 회복의 기초",
                point1: {
                    part1: "다음 사이에 강한 양의 상관관계(0.86)가 있습니다:",
                    part2: "깊은 수면 시간(total_rem_duration)",
                    part3: "과",
                    part4: "REM 일관성 비율 (정신 회복)",
                    part5: "."
                },
                point2: "충분한 깊은 수면을 확보하는 것은 REM 수면의 일관성을 높이고 정신 회복을 촉진하는 데 필수적입니다."
            },
            rec1: {
                title: "총 수면 시간 우선순위",
                point1: "현재 6시간 39분은 너무 짧습니다.",
                point2: "수면 점수는 수면 시간과 중간 정도의 상관관계(0.49)를 보입니다.",
                point3: "침대에 있는 시간을 15-30분씩 꾸준히 늘려 7시간 이상의 총 수면 시간을 달성하세요."
            },
            rec2: {
                title: "수면 방해 최소화",
                point1: {
                    part1: "높은",
                    part2: "각성 비율 (17.0%)",
                    part3: "은 연속적인 수면에 문제가 있음을 나타냅니다."
                },
                point2: "취침 2-3시간 전에 카페인과 알코올을 피하여 수면 위생을 개선하세요.",
                point3: "침실 온도를 약간 시원하게 유지하여 불안정함을 방지하고 각성 비율을 줄이세요."
            },
            rec3: {
                title: "REM 품질 최적화",
                deepSleepLabel: "깊은 수면 비율을 위해:",
                remLabel: "REM 일관성 비율을 위해:",
                point1: "수면 전 가벼운 이완을 실천하여 심박수를 낮추고 깊은 휴식으로의 진입을 가속화하세요.",
                point2: "완전히 어둡고 조용한 수면 환경을 유지하여 수면 단계 중 방해를 예방하세요."
            }
        },
        footer: {
            copyright: "© 2025. All rights reserved."
        }
    }
};
